version: '3'
services:
  pypy-template:
    image: pyt
    container_name: pyt
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
    - "8888:8888" # Jupyter
    volumes:
    - .:/workspace
    tty: true